In [1]:
import pandas as pd
import numpy as np

## Some manipulations for Match Table (Check the nulls and how we can handle it)

In [3]:
match = pd.read_csv('./MatchTable.csv', index_col = 0)

In [4]:
match

,Home Name,Away Name,Season,Stadium Name,Home Possession %,Away Possession %,Home Shots,Away Shots,Home Yellow cards,Away Yellow cards,Home Fouls conceded,Away Fouls conceded,Home Red cards,Away Red cards,Home Goals,Away Goals
0,Crystal Palace,Arsenal,2021/22,Selhurst Park,31.4,68.6,6,12,0,2,11,15,0,0,3,0
1,West Ham United,Everton,2021/22,London Stadium,55.7,44.3,11,13,1,2,9,12,0,1,2,1
2,Tottenham Hotspur,Newcastle United,2021/22,Tottenham Hotspur Stadium,60.8,39.2,19,8,2,3,10,7,0,0,5,1
3,Liverpool,Watford,2021/22,Anfield,73.1,26.9,20,5,1,1,9,8,0,0,2,0
4,Brighton and Hove Albion,Norwich City,2021/22,Amex Stadium,63.0,37.0,31,6,1,1,12,11,0,0,0,0
5,Burnley,Manchester City,2021/22,Turf Moor,23.3,76.7,3,18,1,0,11,6,0,0,0,2
6,Chelsea,Brentford,2021/22,Stamford Bridge,70.6,29.4,21,17,0,0,11,7,0,0,1,4
7,Leeds United,Southampton,2021/22,Elland Road,55.8,44.2,12,14,1,1,14,7,0,0,1,1
8,Wolverhampton Wanderers,Aston Villa,2021/22,Molineux Stadium,48.3,51.7,11,15,4,3,15,8,0,0,2,1
9,Manchester United,Leicester City,2021/22,Old Trafford,53.9,46.1,11,11,2,2,13,6,0,0,1,1
10,Leicester City,Brentford,2021/22,King Power Stadium,52.8,47.2,12,15,1,2,10,10,0,0,2,1
11,Tottenham Hotspur,West Ham United,2021/22,Tottenham Hotspur Stadium,52.7,47.3,17,6,0,1,7,7,0,0,3,1
12,Aston Villa,Arsenal,2021/22,Villa Park,47.0,53.0,8,10,3,3,13,14,0,0,0,1
13,Wolverhampton Wanderers,Leeds United,2021/22,Molineux Stadium,47.8,52.2,14,15,1,5,13,14,1,0,2,3
14,Everton,Newcastle United,2021/22,Goodison Park,38.3,61.7,9,17,2,1,13,11,1,0,1,0
15,Brighton and Hove Albion,Tottenham Hotspur,2021/22,Amex Stadium,48.2,51.8,15,17,2,2,11,9,0,0,0,2
16,Arsenal,Liverpool,2021/22,Emirates Stadium,48.4,51.6,9,9,0,1,9,9,0,0,0,2
17,Crystal Palace,Manchester City,2021/22,Selhurst Park,26.2,73.8,7,19,3,1,6,11,0,0,0,0
18,Chelsea,Newcastle United,2021/22,Stamford Bridge,72.8,27.2,8,7,4,3,17,17,0,0,1,0
19,Everton,Wolverhampton Wanderers,2021/22,Goodison Park,38.0,62.0,7,14,2,1,13,11,1,0,0,1
20,Leeds United,Norwich City,2021/22,Elland Road,52.5,47.5,13,12,3,1,18,8,0,0,2,1
21,Southampton,Watford,2021/22,St. Mary's Stadium,62.5,37.5,13,9,3,2,8,12,0,0,1,2
22,West Ham United,Aston Villa,2021/22,London Stadium,47.1,52.9,11,13,1,0,9,3,0,0,2,1
23,Arsenal,Leicester City,2021/22,Emirates Stadium,46.0,54.0,21,6,0,3,8,10,0,0,2,0
24,Brighton and Hove Albion,Liverpool,2021/22,Amex Stadium,51.8,48.2,8,18,3,1,12,15,0,0,0,2
25,Brentford,Burnley,2021/22,Brentford Community Stadium,54.9,45.1,13,7,1,1,6,10,0,1,2,0
26,Manchester United,Tottenham Hotspur,2021/22,Old Trafford,43.5,56.5,10,10,2,1,8,7,0,0,3,2
27,Norwich City,Chelsea,2021/22,Carrow Road,33.7,66.3,8,15,0,2,8,15,0,0,1,3
28,Southampton,Newcastle United,2021/22,St. Mary's Stadium,67.8,32.2,14,8,1,1,6,7,0,0,1,2
29,Wolverhampton Wanderers,Watford,2021/22,Molineux Stadium,65.8,34.2,10,9,2,2,11,10,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408,Manchester United,Tottenham Hotspur,2018/19,Old Trafford,57.0,43.0,23,9,2,3,11,16,0,0,0,3
1409,Watford,Crystal Palace,2018/19,Vicarage Road,43.7,56.3,13,9,4,2,14,11,0,0,2,1
1410,Fulham,Burnley,2018/19,Craven Cottage,63.8,36.2,25,12,2,1,11,8,0,0,4,2
1411,Newcastle United,Chelsea,2018/19,St. James' Park,18.9,81.1,6,15,3,1,16,8,0,0,1,2
1412,Wolverhampton Wanderers,Manchester City,2018/19,Molineux Stadium,28.9,71.1,11,18,1,2,13,8,0,0,1,1
1413,AFC Bournemouth,Everton,2018/19,Vitality Stadium,49.9,50.1,17,11,0,3,12,10,1,1,2,2
1414,Arsenal,West Ham United,2018/19,Emirates Stadium,61.5,38.5,17,13,1,3,16,13,0,0,3,1
1415,Huddersfield Town,Cardiff City,2018/19,John Smith's Stadium,58.0,42.0,5,14,0,1,8,10,1,0,0,0
1416,Southampton,Leicester City,2018/19,St. Mary's Stadium,51.7,48.3,11,8,1,1,13,11,1,0,1,2
1417,Liverpool,Brighton and Hove Albion,2018/19,Anfield,70.0,30.0,22,6,1,1,8,14,0,0,1,0
1418,Crystal Palace,Liverpool,2018/19,Selhurst Park,36.8,63.2,8,16,1,1,6,13,1,0,0,2
1419,Burnley,Watford,2018/19,Turf Moor,58.4,41.6,8,9,1,2,8,19,0,0,1,3
1420,Manchester City,Huddersfield Town,2018/19,Etihad Stadium,76.9,23.1,32,5,0,2,9,4,0,0,6,1
1421,Brighton and Hove Albion,Manchester United,2018/19,Amex Stadium,33.4,66.6,6,9,1,1,16,13,0,0,3,2
1422,Cardiff City,Newcastle United,2018/19,Cardiff City Stadium,51.3,48.7,12,12,2,2,14,16,0,1,0,0
1423,Everton,Southampton,2018/19,Goodison Park,58.0,42.0,13,15,0,5,8,20,0,0,2,1
1424,Leicester City,Wolverhampton Wanderers,2018/19,King Power Stadium,42.8,57.2,6,11,2,1,10,8,1,0,2,0
1425,Tottenham Hotspur,Fulham,2018/19,Wembley Stadium,59.6,40.4,25,10,0,0,9,5,0,0,3,1
1426,West Ham United,AFC Bournemouth,2018/19,London Stadium,61.0,39.0,11,12,6,2,14,10,0,0,1,2
1427,Chelsea,Arsenal,2018/19,Stamford Bridge,62.3,37.7,24,15,0,2,12,9,0,0,3,2
1428,Liverpool,West Ham United,2018/19,Anfield,64.8,35.2,18,5,1,2,14,9,0,0,4,0
1429,Southampton,Burnley,2018/19,St. Mary's Stadium,47.7,52.3,18,16,0,1,10,9,0,0,0,0
1430,Arsenal,Manchester City,2018/19,Emirates Stadium,42.0,58.0,9,17,2,2,11,14,0,0,0,2
1431,Newcastle United,Tottenham Hotspur,2018/19,St. James' Park,40.4,59.6,15,15,2,2,11,12,0,0,1,2
1432,AFC Bournemouth,Cardiff City,2018/19,Vitality Stadium,62.9,37.1,12,10,1,1,11,9,0,0,2,0
1433,Fulham,Crystal Palace,2018/19,Craven Cottage,66.3,33.7,15,12,1,2,9,11,0,0,0,2
1434,Huddersfield Town,Chelsea,2018/19,John Smith's Stadium,37.2,62.8,6,13,2,1,9,8,0,0,0,3
1435,Watford,Brighton and Hove Albion,2018/19,Vicarage Road,53.2,46.8,19,6,2,2,10,16,0,0,2,0
1436,Wolverhampton Wanderers,Everton,2018/19,Molineux Stadium,57.4,42.6,11,8,0,1,8,7,0,1,2,2
1437,Manchester United,Leicester City,2018/19,Old Trafford,46.3,53.7,8,13,2,1,11,8,0,0,2,1

In [18]:
df.duplicated().sum()

0

In [21]:
df.isnull().sum().sum()

0

In [5]:
new_df = pd.DataFrame()

In [8]:
df = match

In [9]:
new_df['Home Name'] = df['Home Name']
new_df['Away Name'] = df['Away Name']
new_df['Season']    = df['Season']
new_df['Stadium Name'] = df['Stadium Name']
new_df['Home Possession %'] = df['Home Possession %']
new_df['Away Possession %'] = df['Away Possession %']
new_df['Home Shots']=df['Home Shots']
new_df['Away Shots']=df['Away Shots']
new_df['Home Yellow cards'] = df['Home Yellow cards']
new_df['Away Yellow cards'] = df['Away Yellow cards']
new_df['Home Fouls conceded'] = df['Home Fouls conceded']
new_df['Away Fouls conceded'] = df['Away Fouls conceded']
new_df['Home Red cards'] = df['Home Red cards']
new_df['Away Red cards'] = df['Away Red cards']
new_df['Home Goals'] = df['Home Goals']
new_df['Away Goals'] = df['Away Goals']

In [10]:
df.columns

Index([u'Home Name', u'Away Name', u'Season', u'Stadium Name',
       u'Home Possession %', u'Away Possession %', u'Home Shots',
       u'Away Shots', u'Home Yellow cards', u'Away Yellow cards',
       u'Home Fouls conceded', u'Away Fouls conceded', u'Home Red cards',
       u'Away Red cards', u'Home Goals', u'Away Goals'],
      dtype='object')

In [11]:
new_df

,Home Name,Away Name,Season,Stadium Name,Home Possession %,Away Possession %,Home Shots,Away Shots,Home Yellow cards,Away Yellow cards,Home Fouls conceded,Away Fouls conceded,Home Red cards,Away Red cards,Home Goals,Away Goals
0,Crystal Palace,Arsenal,2021/22,Selhurst Park,31.4,68.6,6,12,0,2,11,15,0,0,3,0
1,West Ham United,Everton,2021/22,London Stadium,55.7,44.3,11,13,1,2,9,12,0,1,2,1
2,Tottenham Hotspur,Newcastle United,2021/22,Tottenham Hotspur Stadium,60.8,39.2,19,8,2,3,10,7,0,0,5,1
3,Liverpool,Watford,2021/22,Anfield,73.1,26.9,20,5,1,1,9,8,0,0,2,0
4,Brighton and Hove Albion,Norwich City,2021/22,Amex Stadium,63.0,37.0,31,6,1,1,12,11,0,0,0,0
5,Burnley,Manchester City,2021/22,Turf Moor,23.3,76.7,3,18,1,0,11,6,0,0,0,2
6,Chelsea,Brentford,2021/22,Stamford Bridge,70.6,29.4,21,17,0,0,11,7,0,0,1,4
7,Leeds United,Southampton,2021/22,Elland Road,55.8,44.2,12,14,1,1,14,7,0,0,1,1
8,Wolverhampton Wanderers,Aston Villa,2021/22,Molineux Stadium,48.3,51.7,11,15,4,3,15,8,0,0,2,1
9,Manchester United,Leicester City,2021/22,Old Trafford,53.9,46.1,11,11,2,2,13,6,0,0,1,1
10,Leicester City,Brentford,2021/22,King Power Stadium,52.8,47.2,12,15,1,2,10,10,0,0,2,1
11,Tottenham Hotspur,West Ham United,2021/22,Tottenham Hotspur Stadium,52.7,47.3,17,6,0,1,7,7,0,0,3,1
12,Aston Villa,Arsenal,2021/22,Villa Park,47.0,53.0,8,10,3,3,13,14,0,0,0,1
13,Wolverhampton Wanderers,Leeds United,2021/22,Molineux Stadium,47.8,52.2,14,15,1,5,13,14,1,0,2,3
14,Everton,Newcastle United,2021/22,Goodison Park,38.3,61.7,9,17,2,1,13,11,1,0,1,0
15,Brighton and Hove Albion,Tottenham Hotspur,2021/22,Amex Stadium,48.2,51.8,15,17,2,2,11,9,0,0,0,2
16,Arsenal,Liverpool,2021/22,Emirates Stadium,48.4,51.6,9,9,0,1,9,9,0,0,0,2
17,Crystal Palace,Manchester City,2021/22,Selhurst Park,26.2,73.8,7,19,3,1,6,11,0,0,0,0
18,Chelsea,Newcastle United,2021/22,Stamford Bridge,72.8,27.2,8,7,4,3,17,17,0,0,1,0
19,Everton,Wolverhampton Wanderers,2021/22,Goodison Park,38.0,62.0,7,14,2,1,13,11,1,0,0,1
20,Leeds United,Norwich City,2021/22,Elland Road,52.5,47.5,13,12,3,1,18,8,0,0,2,1
21,Southampton,Watford,2021/22,St. Mary's Stadium,62.5,37.5,13,9,3,2,8,12,0,0,1,2
22,West Ham United,Aston Villa,2021/22,London Stadium,47.1,52.9,11,13,1,0,9,3,0,0,2,1
23,Arsenal,Leicester City,2021/22,Emirates Stadium,46.0,54.0,21,6,0,3,8,10,0,0,2,0
24,Brighton and Hove Albion,Liverpool,2021/22,Amex Stadium,51.8,48.2,8,18,3,1,12,15,0,0,0,2
25,Brentford,Burnley,2021/22,Brentford Community Stadium,54.9,45.1,13,7,1,1,6,10,0,1,2,0
26,Manchester United,Tottenham Hotspur,2021/22,Old Trafford,43.5,56.5,10,10,2,1,8,7,0,0,3,2
27,Norwich City,Chelsea,2021/22,Carrow Road,33.7,66.3,8,15,0,2,8,15,0,0,1,3
28,Southampton,Newcastle United,2021/22,St. Mary's Stadium,67.8,32.2,14,8,1,1,6,7,0,0,1,2
29,Wolverhampton Wanderers,Watford,2021/22,Molineux Stadium,65.8,34.2,10,9,2,2,11,10,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408,Manchester United,Tottenham Hotspur,2018/19,Old Trafford,57.0,43.0,23,9,2,3,11,16,0,0,0,3
1409,Watford,Crystal Palace,2018/19,Vicarage Road,43.7,56.3,13,9,4,2,14,11,0,0,2,1
1410,Fulham,Burnley,2018/19,Craven Cottage,63.8,36.2,25,12,2,1,11,8,0,0,4,2
1411,Newcastle United,Chelsea,2018/19,St. James' Park,18.9,81.1,6,15,3,1,16,8,0,0,1,2
1412,Wolverhampton Wanderers,Manchester City,2018/19,Molineux Stadium,28.9,71.1,11,18,1,2,13,8,0,0,1,1
1413,AFC Bournemouth,Everton,2018/19,Vitality Stadium,49.9,50.1,17,11,0,3,12,10,1,1,2,2
1414,Arsenal,West Ham United,2018/19,Emirates Stadium,61.5,38.5,17,13,1,3,16,13,0,0,3,1
1415,Huddersfield Town,Cardiff City,2018/19,John Smith's Stadium,58.0,42.0,5,14,0,1,8,10,1,0,0,0
1416,Southampton,Leicester City,2018/19,St. Mary's Stadium,51.7,48.3,11,8,1,1,13,11,1,0,1,2
1417,Liverpool,Brighton and Hove Albion,2018/19,Anfield,70.0,30.0,22,6,1,1,8,14,0,0,1,0
1418,Crystal Palace,Liverpool,2018/19,Selhurst Park,36.8,63.2,8,16,1,1,6,13,1,0,0,2
1419,Burnley,Watford,2018/19,Turf Moor,58.4,41.6,8,9,1,2,8,19,0,0,1,3
1420,Manchester City,Huddersfield Town,2018/19,Etihad Stadium,76.9,23.1,32,5,0,2,9,4,0,0,6,1
1421,Brighton and Hove Albion,Manchester United,2018/19,Amex Stadium,33.4,66.6,6,9,1,1,16,13,0,0,3,2
1422,Cardiff City,Newcastle United,2018/19,Cardiff City Stadium,51.3,48.7,12,12,2,2,14,16,0,1,0,0
1423,Everton,Southampton,2018/19,Goodison Park,58.0,42.0,13,15,0,5,8,20,0,0,2,1
1424,Leicester City,Wolverhampton Wanderers,2018/19,King Power Stadium,42.8,57.2,6,11,2,1,10,8,1,0,2,0
1425,Tottenham Hotspur,Fulham,2018/19,Wembley Stadium,59.6,40.4,25,10,0,0,9,5,0,0,3,1
1426,West Ham United,AFC Bournemouth,2018/19,London Stadium,61.0,39.0,11,12,6,2,14,10,0,0,1,2
1427,Chelsea,Arsenal,2018/19,Stamford Bridge,62.3,37.7,24,15,0,2,12,9,0,0,3,2
1428,Liverpool,West Ham United,2018/19,Anfield,64.8,35.2,18,5,1,2,14,9,0,0,4,0
1429,Southampton,Burnley,2018/19,St. Mary's Stadium,47.7,52.3,18,16,0,1,10,9,0,0,0,0
1430,Arsenal,Manchester City,2018/19,Emirates Stadium,42.0,58.0,9,17,2,2,11,14,0,0,0,2
1431,Newcastle United,Tottenham Hotspur,2018/19,St. James' Park,40.4,59.6,15,15,2,2,11,12,0,0,1,2
1432,AFC Bournemouth,Cardiff City,2018/19,Vitality Stadium,62.9,37.1,12,10,1,1,11,9,0,0,2,0
1433,Fulham,Crystal Palace,2018/19,Craven Cottage,66.3,33.7,15,12,1,2,9,11,0,0,0,2
1434,Huddersfield Town,Chelsea,2018/19,John Smith's Stadium,37.2,62.8,6,13,2,1,9,8,0,0,0,3
1435,Watford,Brighton and Hove Albion,2018/19,Vicarage Road,53.2,46.8,19,6,2,2,10,16,0,0,2,0
1436,Wolverhampton Wanderers,Everton,2018/19,Molineux Stadium,57.4,42.6,11,8,0,1,8,7,0,1,2,2
1437,Manchester United,Leicester City,2018/19,Old Trafford,46.3,53.7,8,13,2,1,11,8,0,0,2,1

In [12]:
for indx in new_df.columns:
    if indx in df.columns is None:
        print('Wrong!')
    else:
        print('Okay')

Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay
Okay

In [15]:
new_df.to_csv(r'MatchTableFinal.csv', index=False)

## Club Table

In [22]:
club = pd.read_csv('./ClubTable.csv', index_col = 0)

In [23]:
club

,club Name,Stadium Name,Official Website
0,Arsenal,Emirates Stadium,www.arsenal.com
1,Aston Villa,Villa Park,www.avfc.co.uk
2,Brentford,Brentford Community Stadium,www.brentfordfc.com
3,Brighton and Hove Albion,Amex Stadium,www.brightonandhovealbion.com
4,Burnley,Turf Moor,www.burnleyfootballclub.com
5,Chelsea,Stamford Bridge,www.chelseafc.com
6,Crystal Palace,Selhurst Park,www.cpfc.co.uk
7,Everton,Goodison Park,www.evertonfc.com
8,Leeds United,Elland Road,www.leedsunited.com/
9,Leicester City,King Power Stadium,www.lcfc.com
10,Liverpool,Anfield,www.liverpoolfc.com
11,Manchester City,Etihad Stadium,www.mancity.com
12,Manchester United,Old Trafford,www.manutd.com
13,Newcastle United,St. James' Park,www.nufc.co.uk
14,Norwich City,Carrow Road,www.canaries.co.uk
15,Southampton,St. Mary's Stadium,www.southamptonfc.com
16,Tottenham Hotspur,Tottenham Hotspur Stadium,www.tottenhamhotspur.com
17,Watford,Vicarage Road,www.watfordfc.com
18,West Ham United,London Stadium,www.whufc.com
19,Wolverhampton Wanderers,Molineux Stadium,https://www.wolves.co.uk
20,Fulham,Craven Cottage,www.fulhamfc.com
21,Sheffield United,Bramall Lane,https://www.sufc.co.uk/
22,West Bromwich Albion,The Hawthorns,www.wba.co.uk
23,AFC Bournemouth,Vitality Stadium,www.afcb.co.uk
24,Cardiff City,Cardiff City Stadium,www.cardiffcityfc.co.uk
25,Huddersfield Town,John Smith's Stadium,www.htafc.com
26,Tottenham Hotspur,Wembley Stadium,www.tottenhamhotspur.com

In [25]:
club.isnull().sum()

club Name           0
Stadium Name        0
Official Website    0
dtype: int64

In [28]:
club.duplicated().sum()

0

In [29]:
club.to_csv(r'ClubTableFinal.csv', index=False)

## Stadium Table

In [30]:
stadium = pd.read_csv('./StadiumTable.csv', index_col = 0)

In [31]:
stadium

,Stadium Name,Capacity,Record PL attendance,Building Year,Pitch Length,Pitch Width,Street,City,Postal Code
0,Emirates Stadium,60260,60161,2006,105.00,68.0,75 Drayton Park,London,N5 1BU
1,Villa Park,42682,42045,1897,105.00,68.0,Trinity Road,Birmingham,B6 6HE
2,Brentford Community Stadium,17250,17094,2020,105.00,68.0,Lionel Road South,Brentford,TW8 0RU
3,Amex Stadium,30666,30565,2011,105.00,68.0,Village Way,Brighton,BN1 9BL
4,Turf Moor,21944,21870,1883,105.00,68.0,52-56 Harry Potts Way,Burnley,BB10 4BX
5,Stamford Bridge,40853,42332,1877,103.00,67.5,Fulham Road,London,SW6 1HS
6,Selhurst Park,25486,30115,1924,101.00,68.0,Holmesdale Road,London,SE25 6PU
7,Goodison Park,39221,40552,1892,100.48,68.0,Goodison Road,Liverpool,L4 4EL
8,Elland Road,37890,57892,1897,106.00,69.0,Elland Road,Leeds,LS11 0ES
9,King Power Stadium,32273,32242,2002,105.00,68.0,Filbert Way,Leicester,LE2 7FL
10,Anfield,53394,53292,1884,101.00,68.0,Anfield Road,Liverpool,L4 0TH
11,Etihad Stadium,55017,54693,2002,105.00,68.0,Etihad Campus,Manchester,M11 3FF
12,Old Trafford,74879,76098,1909,105.00,68.0,Old Trafford,Manchester,M16 0RA
13,St. James' Park,52305,52490,1892,105.00,68.0,St. James' Park,NewcastleUponTyne,NE1 4ST
14,Carrow Road,27359,27244,1935,104.00,68.0,Carrow Road,Norwich,NR1 1JE
15,St. Mary's Stadium,32384,32151,2001,105.00,68.0,Britannia Road,Southampton,SO14 5FP
16,Tottenham Hotspur Stadium,62062,61104,2019,100.00,67.0,782 High Rd,London,N17 0BX
17,Vicarage Road,21000,21590,1922,105.00,68.0,Watford,Hertfordshire,WD18 0ER
18,London Stadium,60000,59946,2011,105.00,68.0,Queen Elizabeth Olympic Park,London,E20 2ST
19,Molineux Stadium,32050,31322,1889,105.00,68.0,Waterloo Rd,Wolverhampton,WV1 4QR
20,Craven Cottage,19000,19359,1896,100.00,65.0,Stevenage Road,London,SW6 6HH
21,Bramall Lane,32050,68287,1855,102.00,66.0,Bramall Lane,Sheffield,S2 4SU
22,The Hawthorns,26688,27751,1900,105.00,68.0,Halfords Ln,West Bromwich,B71 4LF
23,Vitality Stadium,11329,11459,1910,105.00,68.0,Dean Court Rd,Bournemouth,BH7 7AF
24,Cardiff City Stadium,33316,32321,2009,105.00,68.0,Leckwith Road,Cardiff,CF11 8AZ
25,John Smith's Stadium,24169,24426,1994,106.00,68.0,Stadium Way,Huddersfield,HD1 6PX
26,Wembley Stadium,90000,85512,2007,105.00,68.0,Rutherford Way,London,HA9 0WS

In [32]:
stadium.to_csv(r'StadiumTableFinal.csv', index=False)

## Player Table

In [241]:
player = pd.read_csv('./PlayerTable.csv', index_col = 0)

In [242]:
X = player[~player['Weight(kg)'].isnull()]

In [243]:
player.head()

,Player Name,Club Name,Season,Position,Nationality,Date Of Birth,Height(cm),Weight(kg)
0,Aaron Ramsey,Aston Villa,2021/22,Midfielder,England,21/01/2003,NaN,NaN
1,Max Aarons,Norwich City,2021/22,Defender,England,04/01/2000,178.0,69.0
2,Abdul Rahman Baba,Chelsea,2021/22,Defender,Ghana,02/07/1994,180.0,NaN
3,Tammy Abraham,Chelsea,2021/22,Forward,England,02/10/1997,190.0,NaN
4,Adam Armstrong,Southampton,2021/22,Forward,England,10/02/1997,172.0,69.0

In [244]:
player[player['Height(cm)'] >200]

,Player Name,Club Name,Season,Position,Nationality,Date Of Birth,Height(cm),Weight(kg)
304,Fraser Forster,Southampton,2021/22,Goalkeeper,England,17/03/1988,201.0,93.0
436,Lovre Kalinic,Aston Villa,2021/22,Goalkeeper,Croatia,03/04/1990,201.0,NaN
774,Kjell Scherpen,Brighton and Hove Albion,2021/22,Goalkeeper,Netherlands,23/01/2000,204.0,98.0
1100,Matt Macey,Arsenal,2020/21,Goalkeeper,England,09/09/1994,205.0,NaN
1264,Peter Crouch,Burnley,2019/20,Forward,England,30/01/1981,201.0,NaN
1668,Costel Pantilimon,Watford,2018/19,Goalkeeper,Romania,01/02/1987,203.0,NaN

In [245]:
player.duplicated().sum()

0

In [246]:
player.isnull().sum()

Player Name         0
Club Name           1
Season              0
Position            0
Nationality         0
Date Of Birth       6
Height(cm)        355
Weight(kg)       1275
dtype: int64

In [247]:
list_ = player[player['Club Name'].isnull()].index.tolist()
list_

[530]

In [248]:
player.iloc[530]

Player Name      Ainsley Maitland-Niles
Club Name                           NaN
Season                          2021/22
Position                     Midfielder
Nationality                     Algeria
Date Of Birth                21/02/1991
Height(cm)                          179
Weight(kg)                           67
Name: 530, dtype: object

In [249]:
player.iloc[530,1] = 'Arsenal'

In [250]:
player.iloc[530]

Player Name      Ainsley Maitland-Niles
Club Name                       Arsenal
Season                          2021/22
Position                     Midfielder
Nationality                     Algeria
Date Of Birth                21/02/1991
Height(cm)                          179
Weight(kg)                           67
Name: 530, dtype: object

In [251]:
player[player['Date Of Birth'].isnull()].index.tolist()

[300, 438, 813, 824, 1101, 1328]

In [252]:
player.iloc[300,5] = '05/05/2004'

In [253]:
player.iloc[438,5] = '01/04/1997'

In [255]:
player.iloc[813,5] = '22/09/2002'

In [256]:
player.iloc[824,5] = '16/02/1982'

In [258]:
player.iloc[1101,5] = '19/10/2002'

In [259]:
player.iloc[1328,5]='17/08/2000'

In [267]:
player.isnull().sum()

Player Name         0
Club Name           0
Season              0
Position            0
Nationality         0
Date Of Birth       0
Height(cm)        355
Weight(kg)       1275
dtype: int64

In [269]:
player.drop(['Club Name', 'Season'], axis=1, inplace=True)

In [272]:
player.to_csv(r'PlayerTableFinal.csv', index=False)

## PlaysFor Table

In [55]:
playsFor = pd.read_csv('./PlaysForTable.csv', index_col = 0)

In [56]:
playsFor.isnull().sum()

Club Name      0
Season         0
Player Name    0
dtype: int64

In [64]:
playsFor[playsFor['Player Name'] == 'Matej Ková&#345;']

              Club Name   Season       Player Name
1356  Manchester United  2020/21  Matej Ková&#345;
2400  Manchester United  2019/20  Matej Ková&#345;
3539  Manchester United  2018/19  Matej Ková&#345;

In [82]:
playsFor.iloc[1356,2] = 'Matej Kovář'
playsFor.iloc[2400,2] = 'Matej Kovář'
playsFor.iloc[3539,2] = 'Matej Kovář'

In [83]:
playsFor[playsFor['Player Name'] == 'Bojan Radulovi&#263;']

                     Club Name   Season           Player Name
1931  Brighton and Hove Albion  2019/20  Bojan Radulovi&#263;

In [84]:
playsFor.iloc[1931,2] = 'Bojan Radulović'

In [93]:
playsFor[playsFor['Player Name'].str.contains(';')]

Empty DataFrame
Columns: [Club Name, Season, Player Name]
Index: []

In [94]:
playsFor.to_csv(r'PlaysForTableFinal.csv', index=False)

## Creating User Table

In [96]:
cols = ['Email', 'UserName', 'Password', 'Gender', 'BirthDate','FavouriteClubName']

In [103]:
records = [{
    
    'Email': 'mohamedayman15069@aucegypt.edu',
    'UserName':'Immortal_warLock', 
    'Password':"0123456789",
    'Gender'  : 'M',
    'BirthDate':'12/3/2000',
    'FavouriteClubName': 'Manchester City'
    
},
    {
    'Email' : 'ahmed@gmail.com',
    'UserName':"ahmed_",
    'Password':'04567893',
    'Gender'  : 'M',
    'BirthDate':'12/1/1995',
    'FavouriteClubName':'Liverpool'},
    {
        'Email':'Amer@aucegypt.edu',
        'UserName':'Amer',
        'Password':'123456789',
        'Gender'  : 'M',
        'BirthDate':'15/6/2001',
        'FavouriteClubName':'Arsenal'
    }
]

In [106]:
user = pd.DataFrame(records, columns = cols)

In [107]:
user

,Email,UserName,Password,Gender,BirthDate,FavouriteClubName
0,mohamedayman15069@aucegypt.edu,Immortal_warLock,0123456789,M,12/3/2000,Manchester City
1,ahmed@gmail.com,ahmed_,04567893,M,12/1/1995,Liverpool
2,Amer@aucegypt.edu,Amer,123456789,M,15/6/2001,Arsenal

In [111]:
user.to_csv(r'UserTableFinal.csv', index=False)

## Creating Review Table

In [109]:
cols = ['Email', 'MatchSeason', 'HomeClubName', 'AwayClubName',
'rating', 'TextReview']

In [110]:
records = [
    
    {
        'Email': 'mohamedayman15069@aucegypt.edu',
        'MatchSeason':'21/2020',
        'HomeClubName':"Arsenal",
        'AwayClubName':"Manchester City",
        'rating': '0.6',
        'TextReview':'Good Match'
    }
]

In [112]:
review = pd.DataFrame(records, columns = cols)
review.to_csv(r'ReviewTableFinal.csv', index=False)